-- 2021년에 가입한 회원 중 상품을 구매한 회원수와 상품을 구매한 회원수 비율
-- 년, 월 별로 출력
WITH USER_21 AS (
    SELECT DISTINCT USER_ID
    FROM USER_INFO
    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
)
SELECT YEAR(SALES_DATE) AS YEAR
    , MONTH(SALES_DATE) AS MONTH
    , COUNT(DISTINCT o.USER_ID) AS PURCHASED_USERS
    , ROUND(COUNT(DISTINCT o.USER_ID) / (SELECT COUNT(*) FROM USER_21),1) AS PUCHASED_RATIO
FROM USER_INFO u
    JOIN ONLINE_SALE o
    ON u.USER_ID = o.USER_ID AND u.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY 1,2
ORDER BY 1,2